---
    name: Gataria CI/CD Dev
    on:
      push:
        branches:
          - dev
    
    jobs:
      build-dev:
        name: Build dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        steps:
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Docker login
          run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Docker build
          run: docker build -t evermariano/gataria-frontend:dev$GITHUB_SHA . --build-arg REACT_APP_STAGE=dev
        - name: docker push
          run: docker push evermariano/gataria-frontend:dev$GITHUB_SHA
      test-dev:
        name: Test dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        needs: build-dev
        steps:
        - name: Step 1
          run: env
      deploy-dev:
        name: Deploy dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        needs: test-dev
        steps:
        - name: run command
          run: echo $GITHUB_SHA