---
    name: Gataria CI/CD Dev
    on:
      push:
        branches:
          - dev
    
    jobs:
      build-dev:
        name: Build dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        steps:
        - name: Clone repository
          uses: actions/checkout@v3
        - name: Docker login
          uses: docker/login-action@v1
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Docker build
          run: docker build -t evermariano/gataria-frontend:dev$GITHUB_SHA . --build-arg REACT_APP_STAGE=dev
        - name: docker push
          run: docker push evermariano/gataria-frontend:dev$GITHUB_SHA
      test-dev:
        name: Test dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        needs: build-dev
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
        -  name: run command
           run: npm test
      deploy-dev:
        name: Deploy dev
        if: contains (github.ref, 'dev')
        runs-on: self-hosted
        needs: test-dev
        steps:
        - name: run command
          run: echo $GITHUB_SHA